---
name: Net-KCRW-Playlist
version: 1.0
author:
  - 'Aaron Straup Cope E<lt>ascope@cpan.orgE<gt>'
abstract: Fetch playlist data for the KCRW.org radio station
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Date::Format: 0
  Date::Parse: 0
  HTML::TableExtract: 0
  LWP::UserAgent: 0
build_requires:
  Test::Simple: '>= 0.47'
provides:
  Net::KCRW::Playlist:
    file: lib/Net/KCRW/Playlist.pm
    version: 1.0
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
